// examples/sveltekit/src/routes/+page.svelte
<script lang="ts">
import { Delete, Diamond, DiamondPlus } from '@lucide/svelte';
import { useLiveQuery } from '@tanstack/svelte-db';
import { getTasksCollection, type Task } from '$lib/stores/tasks.svelte';
import { browser } from '$app/environment';
import type { PageData } from './$types';

let { data }: { data: PageData } = $props();

let newTaskText = $state('');
let editingId = $state<string | null>(null);
let editText = $state('');

// Get the collection
const collection = getTasksCollection(data.tasks);

// Use TanStack DB's useLiveQuery - pass the collection directly
// Type assertion needed for same contravariance issue as in tasks.svelte.ts
const query = useLiveQuery(collection as any);

// Reactive data from the query
let tasks = $derived((query.data || []) as Task[]);
let isLoading = $derived(query.isLoading ?? false);
let isError = $derived(query.isError ?? false);

function handleCreateTask(e: Event) {
  e.preventDefault();
  if (newTaskText.trim() && browser) {
    const id = crypto.randomUUID();
    collection.insert({ id, text: newTaskText.trim(), isCompleted: false });
    newTaskText = '';
  }
}

function handleToggleComplete(id: string, isCompleted: boolean) {
  if (browser) {
    collection.update(id, (draft: Task) => {
      draft.isCompleted = !isCompleted;
    });
  }
}

function handleEditStart(id: string, text: string) {
  editingId = id;
  editText = text;
}

function handleEditSave(id: string) {
  if (editText.trim() && browser) {
    collection.update(id, (draft: Task) => {
      draft.text = editText.trim();
    });
    editingId = null;
  }
}

function handleEditCancel() {
  editingId = null;
  editText = '';
}

function handleDelete(id: string) {
  if (browser) {
    collection.delete(id);
  }
}

function handleKeyDown(e: KeyboardEvent, id: string) {
  if (e.key === 'Enter') {
    handleEditSave(id);
  } else if (e.key === 'Escape') {
    handleEditCancel();
  }
}
</script>

<svelte:head>
	<title>Convex TanStack DB - Svelte Demo</title>
</svelte:head>

<div class="p-6 max-w-2xl mx-auto">
	{#if isError}
		<div
			class="bg-rose-pine-surface border-2 border-rose-pine-rose text-rose-pine-text px-6 py-4 rounded-lg shadow-md"
		>
			<h2 class="text-lg font-semibold text-rose-pine-rose mb-2">Error</h2>
			<p class="text-rose-pine-muted mb-4">Failed to load tasks. Please try reloading.</p>
			<button
				type="button"
				onclick={() => window.location.reload()}
				class="px-4 py-2 bg-rose-pine-rose text-rose-pine-base rounded hover:bg-rose-pine-rose/80 transition-colors"
			>
				Retry
			</button>
		</div>
	{:else}
		<form onsubmit={handleCreateTask} class="mb-6">
			<div class="flex gap-2">
				<input
					type="text"
					bind:value={newTaskText}
					placeholder="Add a new task..."
					disabled={!browser}
					class="flex-1 px-3 py-2 border border-rose-pine-muted rounded focus:outline-none focus:border-rose-pine-rose disabled:opacity-50"
				/>
				<button
					type="submit"
					disabled={!newTaskText.trim() || !browser}
					class="px-4 py-2 border border-rose-pine-rose text-rose-pine-text rounded hover:bg-rose-pine-rose hover:text-rose-pine-base disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
				>
					Add
				</button>
			</div>
		</form>

		{#if isLoading}
			<div class="mb-4 text-center">
				<div
					class="inline-block animate-spin rounded-full h-4 w-4 border-b-2 border-rose-pine-gold"
				></div>
				<span class="ml-2 text-rose-pine-muted">Loading...</span>
			</div>
		{/if}

		<div class="space-y-2">
			{#each tasks as task (task.id)}
				<div class="flex items-center gap-3 p-3 border border-rose-pine-muted rounded">
					<button
						type="button"
						onclick={() => handleDelete(task.id)}
						disabled={!browser}
						class="text-rose-pine-rose hover:text-rose-pine-rose/80 transition-colors disabled:opacity-50"
						aria-label="Delete task"
					>
						<Delete class="w-5 h-5" />
					</button>

					<button
						type="button"
						onclick={() => handleToggleComplete(task.id, task.isCompleted)}
						disabled={!browser}
						class="transition-colors disabled:opacity-50 {task.isCompleted
							? 'text-blue hover:text-rose-pine-gold'
							: 'text-rose-pine-gold hover:text-blue'}"
						aria-label={task.isCompleted ? 'Mark as incomplete' : 'Mark as complete'}
					>
						{#if task.isCompleted}
							<DiamondPlus class="w-5 h-5" />
						{:else}
							<Diamond class="w-5 h-5" />
						{/if}
					</button>

					{#if editingId === task.id}
						<div class="flex-1 flex gap-2">
							<input
								type="text"
								bind:value={editText}
								onkeydown={(e) => handleKeyDown(e, task.id)}
								onblur={() => handleEditSave(task.id)}
								class="flex-1 px-2 py-1 border border-rose-pine-muted rounded focus:outline-none focus:border-rose-pine-rose"
							/>
						</div>
					{:else}
						<button
							type="button"
							onclick={() => handleEditStart(task.id, task.text)}
							disabled={!browser}
							class="flex-1 cursor-pointer hover:bg-rose-pine-surface px-2 py-1 rounded text-left disabled:opacity-50 {task.isCompleted
								? 'line-through text-rose-pine-muted'
								: ''}"
						>
							{task.text}
						</button>
					{/if}
				</div>
			{/each}
		</div>

		{#if tasks.length === 0 && !isLoading}
			<p class="text-rose-pine-muted text-center py-8">No tasks yet. Create one above!</p>
		{/if}
	{/if}
</div>

// src/routes/index.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useTasks, useCreateTask, useUpdateTask } from "../useTasks";
import { useState } from "react";

export const Route = createFileRoute('/')({
  component: HomeComponent,
})

function HomeComponent() {
  const [newTaskText, setNewTaskText] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editText, setEditText] = useState("");

  const { data, isLoading, error } = useTasks();
  
  const createTask = useCreateTask();
  const updateTask = useUpdateTask();

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (newTaskText.trim()) {
      try {
        await createTask({ text: newTaskText.trim() });
        setNewTaskText("");
      } catch (error) {
        console.error("Failed to create task:", error);
      }
    }
  };

  const handleToggleComplete = async (id: string, isCompleted: boolean) => {
    try {
      await updateTask(id, { isCompleted: !isCompleted });
    } catch (error) {
      console.error("Failed to toggle task:", error);
    }
  };

  const handleEditStart = (id: string, text: string) => {
    setEditingId(id);
    setEditText(text);
  };

  const handleEditSave = async (id: string) => {
    if (editText.trim()) {
      try {
        await updateTask(id, { text: editText.trim() });
        setEditingId(null);
      } catch (error) {
        console.error("Failed to update task:", error);
      }
    }
  };

  const handleEditCancel = () => {
    setEditingId(null);
    setEditText("");
  };

  if (error) {
    return (
      <div className="p-6 max-w-md mx-auto">
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded">
          Error loading tasks: {String(error)}
        </div>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-md mx-auto">
      <h3 className="text-2xl font-bold mb-6">Task Manager (RxDB)</h3>
      
      {isLoading && (
        <div className="mb-4 text-center">
          <div className="inline-block animate-spin rounded-full h-4 w-4 border-b-2 border-blue-500"></div>
          <span className="ml-2 text-gray-600">Loading...</span>
        </div>
      )}
      
      {/* Create Task Form */}
      <form onSubmit={handleCreateTask} className="mb-6">
        <div className="flex gap-2">
          <input
            type="text"
            value={newTaskText}
            onChange={(e) => setNewTaskText(e.target.value)}
            placeholder="Add a new task..."
            className="flex-1 px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
          />
          <button
            type="submit"
            disabled={!newTaskText.trim() || isLoading}
            className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            Add
          </button>
        </div>
      </form>

      {/* Task List */}
      <div className="space-y-2">
        {data.filter(task => !task._deleted).map((task) => (
          <div key={task.id} className="flex items-center gap-3 p-3 border border-gray-200 rounded-md">
            {/* Toggle Completion Checkbox */}
            <input
              type="checkbox"
              checked={task.isCompleted}
              onChange={() => handleToggleComplete(task.id, task.isCompleted)}
              className="w-4 h-4 text-blue-600 rounded focus:ring-blue-500"
              disabled={isLoading}
            />
            
            {/* Task Text */}
            {editingId === task.id ? (
              <div className="flex-1 flex gap-2">
                <input
                  type="text"
                  value={editText}
                  onChange={(e) => setEditText(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") handleEditSave(task.id);
                    if (e.key === "Escape") handleEditCancel();
                  }}
                  onBlur={() => handleEditSave(task.id)}
                  className="flex-1 px-2 py-1 border border-gray-300 rounded focus:outline-none focus:ring-2 focus:ring-blue-500"
                  autoFocus
                />
              </div>
            ) : (
              <span
                onClick={() => handleEditStart(task.id, task.text)}
                className={`flex-1 cursor-pointer hover:bg-gray-100 px-2 py-1 rounded ${
                  task.isCompleted ? "line-through text-gray-500" : ""
                }`}
              >
                {task.text}
              </span>
            )}
          </div>
        ))}
      </div>

      {data.filter(task => !task._deleted).length === 0 && !isLoading && (
        <p className="text-gray-500 text-center py-8">No tasks yet. Create one above!</p>
      )}
    </div>
  )
}
